title:              Clean Blog
email:              songsyzero@163.com
description:        A Blog Theme by Start Bootstrap
baseurl:            "/lnyyj-clean-blog-jekyll"
url:                "https://lnyyj.github.io"
author:
  name: lnyyj
  url: https://github.com/lnyyj/
  email: songsyzero@163.com

# Social Profiles
twitter_username:   SBootstrap
github_username:    lnyyj
# facebook_username:  lnyyj
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-clean-blog